//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using Common.Schema.Board;
using Common.Schema.Board.Fields;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


namespace Common.Schema.Message.PlayerMessage
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://theprojectgame.mini.pw.edu.pl/")]
    [XmlRoot(Namespace="http://theprojectgame.mini.pw.edu.pl/", IsNullable=false)]
    public partial class Data : PlayerMessage {
    
        private TaskField[] taskFieldsField;
    
        private GoalField[] goalFieldsField;
    
        private Piece[] piecesField;
    
        private Location playerLocationField;
    
        private bool gameFinishedField;
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public TaskField[] TaskFields {
            get {
                return this.taskFieldsField;
            }
            set {
                this.taskFieldsField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public GoalField[] GoalFields {
            get {
                return this.goalFieldsField;
            }
            set {
                this.goalFieldsField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public Piece[] Pieces {
            get {
                return this.piecesField;
            }
            set {
                this.piecesField = value;
            }
        }
    
        /// <remarks/>
        public Location PlayerLocation {
            get {
                return this.playerLocationField;
            }
            set {
                this.playerLocationField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public bool gameFinished {
            get {
                return this.gameFinishedField;
            }
            set {
                this.gameFinishedField = value;
            }
        }
    }
}