//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace Common.Config
{

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/", IsNullable = false)]
    public partial class PlayerSettings : Configuration
    {

        private uint retryJoinGameIntervalField;

        public PlayerSettings()
        {
            this.retryJoinGameIntervalField = ((uint)(5000));
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "5000")]
        public uint RetryJoinGameInterval
        {
            get
            {
                return this.retryJoinGameIntervalField;
            }
            set
            {
                this.retryJoinGameIntervalField = value;
            }
        }
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
    public partial class Configuration
    {

        private uint keepAliveIntervalField;

        public Configuration()
        {
            this.keepAliveIntervalField = ((uint)(30000));
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "30000")]
        public uint KeepAliveInterval
        {
            get
            {
                return this.keepAliveIntervalField;
            }
            set
            {
                this.keepAliveIntervalField = value;
            }
        }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Field))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GoalField))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
    public partial class Location
    {

        private uint xField;

        private uint yField;

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GoalField))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
    public abstract partial class Field : Location
    {
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
    public partial class GoalField : Field
    {

        private GoalFieldType typeField;

        private TeamColour teamField;

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public GoalFieldType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TeamColour team
        {
            get
            {
                return this.teamField;
            }
            set
            {
                this.teamField = value;
            }
        }
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
    public enum GoalFieldType
    {

        /// <uwagi/>
        goal,

        /// <uwagi/>
        [System.Xml.Serialization.XmlEnumAttribute("non-goal")]
        nongoal,
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
    public enum TeamColour
    {

        /// <uwagi/>
        red,

        /// <uwagi/>
        blue,
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/", IsNullable = false)]
    public partial class GameMasterSettings : Configuration
    {

        private GameMasterSettingsGameDefinition gameDefinitionField;

        private GameMasterSettingsActionCosts actionCostsField;

        private uint retryRegisterGameIntervalField;

        public GameMasterSettings()
        {
            this.retryRegisterGameIntervalField = ((uint)(5000));
        }

        /// <uwagi/>
        public GameMasterSettingsGameDefinition GameDefinition
        {
            get
            {
                return this.gameDefinitionField;
            }
            set
            {
                this.gameDefinitionField = value;
            }
        }

        /// <uwagi/>
        public GameMasterSettingsActionCosts ActionCosts
        {
            get
            {
                return this.actionCostsField;
            }
            set
            {
                this.actionCostsField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "5000")]
        public uint RetryRegisterGameInterval
        {
            get
            {
                return this.retryRegisterGameIntervalField;
            }
            set
            {
                this.retryRegisterGameIntervalField = value;
            }
        }
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
    public partial class GameMasterSettingsGameDefinition
    {

        private GoalField[] goalsField;

        private double shamProbabilityField;

        private uint placingNewPiecesFrequencyField;

        private uint initialNumberOfPiecesField;

        private string boardWidthField;

        private string taskAreaLengthField;

        private string goalAreaLengthField;

        private string numberOfPlayersPerTeamField;

        private string gameNameField;

        public GameMasterSettingsGameDefinition()
        {
            this.shamProbabilityField = 0.1D;
            this.placingNewPiecesFrequencyField = ((uint)(1000));
            this.initialNumberOfPiecesField = ((uint)(4));
            this.boardWidthField = "5";
            this.taskAreaLengthField = "7";
            this.goalAreaLengthField = "3";
            this.numberOfPlayersPerTeamField = "4";
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("Goals")]
        public GoalField[] Goals
        {
            get
            {
                return this.goalsField;
            }
            set
            {
                this.goalsField = value;
            }
        }

        /// <uwagi/>
        public double ShamProbability
        {
            get
            {
                return this.shamProbabilityField;
            }
            set
            {
                this.shamProbabilityField = value;
            }
        }

        /// <uwagi/>
        public uint PlacingNewPiecesFrequency
        {
            get
            {
                return this.placingNewPiecesFrequencyField;
            }
            set
            {
                this.placingNewPiecesFrequencyField = value;
            }
        }

        /// <uwagi/>
        public uint InitialNumberOfPieces
        {
            get
            {
                return this.initialNumberOfPiecesField;
            }
            set
            {
                this.initialNumberOfPiecesField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string BoardWidth
        {
            get
            {
                return this.boardWidthField;
            }
            set
            {
                this.boardWidthField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string TaskAreaLength
        {
            get
            {
                return this.taskAreaLengthField;
            }
            set
            {
                this.taskAreaLengthField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string GoalAreaLength
        {
            get
            {
                return this.goalAreaLengthField;
            }
            set
            {
                this.goalAreaLengthField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string NumberOfPlayersPerTeam
        {
            get
            {
                return this.numberOfPlayersPerTeamField;
            }
            set
            {
                this.numberOfPlayersPerTeamField = value;
            }
        }

        /// <uwagi/>
        public string GameName
        {
            get
            {
                return this.gameNameField;
            }
            set
            {
                this.gameNameField = value;
            }
        }
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
    public partial class GameMasterSettingsActionCosts
    {

        private uint moveDelayField;

        private uint discoverDelayField;

        private uint testDelayField;

        private uint pickUpDelayField;

        private uint placingDelayField;

        private uint knowledgeExchangeDelayField;

        public GameMasterSettingsActionCosts()
        {
            this.moveDelayField = ((uint)(100));
            this.discoverDelayField = ((uint)(450));
            this.testDelayField = ((uint)(500));
            this.pickUpDelayField = ((uint)(100));
            this.placingDelayField = ((uint)(100));
            this.knowledgeExchangeDelayField = ((uint)(1200));
        }

        /// <uwagi/>
        public uint MoveDelay
        {
            get
            {
                return this.moveDelayField;
            }
            set
            {
                this.moveDelayField = value;
            }
        }

        /// <uwagi/>
        public uint DiscoverDelay
        {
            get
            {
                return this.discoverDelayField;
            }
            set
            {
                this.discoverDelayField = value;
            }
        }

        /// <uwagi/>
        public uint TestDelay
        {
            get
            {
                return this.testDelayField;
            }
            set
            {
                this.testDelayField = value;
            }
        }

        /// <uwagi/>
        public uint PickUpDelay
        {
            get
            {
                return this.pickUpDelayField;
            }
            set
            {
                this.pickUpDelayField = value;
            }
        }

        /// <uwagi/>
        public uint PlacingDelay
        {
            get
            {
                return this.placingDelayField;
            }
            set
            {
                this.placingDelayField = value;
            }
        }

        /// <uwagi/>
        public uint KnowledgeExchangeDelay
        {
            get
            {
                return this.knowledgeExchangeDelayField;
            }
            set
            {
                this.knowledgeExchangeDelayField = value;
            }
        }
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/", IsNullable = false)]
    public partial class CommunicationServerSettings : Configuration
    {
    }
}
